package api

import config.addTableToCartHeaders._
import config.baseHelpers._
import config.thirtyPersentOfUsersHeaders._
import config.fiftyPersentOfUsersHeaders._
import config.navigateToTablesTabHeaders._
import config.openTableProductCartHeaders._
import config.openTheApplicationHeaders._
import io.gatling.core.Predef._
import io.gatling.core.structure._
import io.gatling.http.Predef._

object main {

  def openTheApplication(): ChainBuilder = {
    exec(
      http("1. Open the application")
        .get("/")
        .headers(openTheApplicationHeader_0)
        .resources(
          http("request_1")
            .options("/api/v1/content/boxes/headerMessage/?lang=en")
            .headers(openTheApplicationHeader_1),
          http("request_2")
            .options("/actuator/health/ping")
            .headers(openTheApplicationHeader_1),
          http("request_3")
            .options("/api/v1/products/group/FEATURED_ITEM?store=DEFAULT&lang=en")
            .headers(openTheApplicationHeader_1),
          http("request_4")
            .get("/api/v1/content/boxes/headerMessage/?lang=en")
            .headers(openTheApplicationHeader_2)
            .check(status.is(404)),
          http("request_5")
            .get("/actuator/health/ping")
            .headers(openTheApplicationHeader_2),
          http("request_6")
            .get("/api/v1/products/group/FEATURED_ITEM?store=DEFAULT&lang=en")
            .headers(openTheApplicationHeader_2),
          http("request_7")
            .get(googleFontsIUri + "?family=Open+Sans:400,600&subset=cyrillic")
            .headers(openTheApplicationHeader_3),
          http("request_8")
            .options("/api/v1/content/pages/?page=0&count=20&store=DEFAULT&lang=en")
            .headers(openTheApplicationHeader_1),
          http("request_9")
            .options("/api/v1/store/DEFAULT")
            .headers(openTheApplicationHeader_1),
          http("request_10")
            .options("/api/v1/category/?count=20&page=0&store=DEFAULT&lang=en")
            .headers(openTheApplicationHeader_1),
          http("request_12")
            .options("/api/v1/product/1/price/")
            .headers(openTheApplicationHeader_5),
          http("request_13")
            .options("/api/v1/product/50/price/")
            .headers(openTheApplicationHeader_5),
          http("request_14")
            .options("/api/v1/product/50/price/")
            .headers(openTheApplicationHeader_5),
          http("request_15")
            .options("/api/v1/product/51/price/")
            .headers(openTheApplicationHeader_5),
          http("request_16")
            .options("/api/v1/product/52/price/")
            .headers(openTheApplicationHeader_5),
          http("request_17")
            .options("/api/v1/product/51/price/")
            .headers(openTheApplicationHeader_5),
          http("request_18")
            .options("/api/v1/product/1/price/")
            .headers(openTheApplicationHeader_5),
          http("request_19")
            .get("/api/v1/store/DEFAULT")
            .headers(openTheApplicationHeader_2),
          http("request_20")
            .get("/api/v1/content/pages/?page=0&count=20&store=DEFAULT&lang=en")
            .headers(openTheApplicationHeader_2),
          http("request_21")
            .options("/api/v1/product/52/price/")
            .headers(openTheApplicationHeader_5),
          http("request_22")
            .post("/api/v1/product/50/price/")
            .headers(openTheApplicationHeader_6)
            .body(RawFileBody("json_files/step1/0022_request.json")),
          http("request_23")
            .post("/api/v1/product/1/price/")
            .headers(openTheApplicationHeader_6)
            .body(RawFileBody("json_files/step1/0023_request.json")),
          http("request_24")
            .get("/api/v1/category/?count=20&page=0&store=DEFAULT&lang=en")
            .headers(openTheApplicationHeader_2),
          http("request_25")
            .post("/api/v1/product/1/price/")
            .headers(openTheApplicationHeader_6)
            .body(RawFileBody("json_files/step1/0025_request.json")),
          http("request_26")
            .post("/api/v1/product/50/price/")
            .headers(openTheApplicationHeader_6)
            .body(RawFileBody("json_files/step1/0026_request.json")),
          http("request_27")
            .post("/api/v1/product/51/price/")
            .headers(openTheApplicationHeader_6)
            .body(RawFileBody("json_files/step1/0027_request.json")),
          http("request_28")
            .post("/api/v1/product/52/price/")
            .headers(openTheApplicationHeader_6)
            .body(RawFileBody("json_files/step1/0028_request.json")),
          http("request_29")
            .post("/api/v1/product/51/price/")
            .headers(openTheApplicationHeader_6)
            .body(RawFileBody("json_files/step1/0029_request.json")),
          http("request_30")
            .post("/api/v1/product/52/price/")
            .headers(openTheApplicationHeader_6)
            .body(RawFileBody("json_files/step1/0030_request.json"))
        )
    )
  }

  def navigateToTablesTab() : ChainBuilder = {
      exec(
        http("2. Navigate to \"Tables\" tab")
          .options("/actuator/health/ping")
          .headers(navigateToTablesTabHeader_0)
          .resources(
            http("request_1")
              .options("/api/v1/content/boxes/headerMessage/?lang=en")
              .headers(navigateToTablesTabHeader_0),
            http("request_2")
              .options("/api/v1/products/?&store=DEFAULT&lang=en&page=0&count=15&category=50")
              .headers(navigateToTablesTabHeader_0),
            http("request_3")
              .get("/actuator/health/ping")
              .headers(navigateToTablesTabHeader_1),
            http("request_4")
              .get("/api/v1/content/boxes/headerMessage/?lang=en")
              .headers(navigateToTablesTabHeader_1)
              .check(status.is(404)),
            http("request_5")
              .get("/api/v1/products/?&store=DEFAULT&lang=en&page=0&count=15&category=50")
              .headers(navigateToTablesTabHeader_1),
            http("request_6")
              .options("/api/v1/store/DEFAULT")
              .headers(navigateToTablesTabHeader_1),
            http("request_7")
              .options("/api/v1/content/pages/?page=0&count=20&store=DEFAULT&lang=en")
              .headers(navigateToTablesTabHeader_0),
            http("request_8")
              .options("/api/v1/category/?count=20&page=0&store=DEFAULT&lang=en")
              .headers(navigateToTablesTabHeader_0),
            http("request_9")
              .get("/api/v1/content/pages/?page=0&count=20&store=DEFAULT&lang=en")
              .headers(navigateToTablesTabHeader_1),
            http("request_10")
              .get("/api/v1/category/?count=20&page=0&store=DEFAULT&lang=en")
              .headers(navigateToTablesTabHeader_1),
            http("request_11")
              .options("/api/v1/product/1/price/")
              .headers(navigateToTablesTabHeader_2),
            http("request_12")
              .get("/api/v1/store/DEFAULT")
              .headers(navigateToTablesTabHeader_1),
            http("request_13")
              .options("/api/v1/category/50?store=DEFAULT&lang=en")
              .headers(navigateToTablesTabHeader_0),
            http("request_14")
              .get("/api/v1/category/50?store=DEFAULT&lang=en")
              .headers(navigateToTablesTabHeader_1),
            http("request_15")
              .post("/api/v1/product/1/price/")
              .headers(navigateToTablesTabHeader_3)
              .body(RawFileBody("json_files/step2/0015_request.json")),
            http("request_16")
              .options("/api/v1/category/50/manufacturers/?store=DEFAULT&lang=en")
              .headers(navigateToTablesTabHeader_0),
            http("request_17")
              .get("/api/v1/category/50/manufacturers/?store=DEFAULT&lang=en")
              .headers(navigateToTablesTabHeader_1),
            http("request_18")
              .options("/api/v1/category/50/variants/?store=DEFAULT&lang=en")
              .headers(navigateToTablesTabHeader_0),
            http("request_19")
              .get("/api/v1/category/50/variants/?store=DEFAULT&lang=en")
              .headers(navigateToTablesTabHeader_1)
              .check(status.is(404))
          )
      )
    }

  def openTableProductCart() : ChainBuilder = {
      exec(
        http("3. Open a table product cart")
          .options("/actuator/health/ping")
          .headers(openTableProductCartHeader_0)
          .resources(
            http("request_1")
              .get("/actuator/health/ping")
              .headers(openTableProductCartHeader_1),
            http("request_2")
              .options("/api/v1/products/1?lang=en&store=DEFAULT")
              .headers(openTableProductCartHeader_0),
            http("request_3")
              .options("/api/v1/content/boxes/headerMessage/?lang=en")
              .headers(openTableProductCartHeader_0),
            http("request_4")
              .options("/api/v1/products/1/reviews?store=DEFAULT")
              .headers(openTableProductCartHeader_0),
            http("request_5")
              .options("/api/v1/store/DEFAULT")
              .headers(openTableProductCartHeader_0),
            http("request_6")
              .get("/api/v1/content/boxes/headerMessage/?lang=en")
              .headers(openTableProductCartHeader_1)
              .check(status.is(404)),
            http("request_7")
              .options("/api/v1/category/?count=20&page=0&store=DEFAULT&lang=en")
              .headers(openTableProductCartHeader_0),
            http("request_8")
              .options("/api/v1/content/pages/?page=0&count=20&store=DEFAULT&lang=en")
              .headers(openTableProductCartHeader_0),
            http("request_9")
              .get("/api/v1/store/DEFAULT")
              .headers(openTableProductCartHeader_1),
            http("request_10")
              .get("/api/v1/products/1/reviews?store=DEFAULT")
              .headers(openTableProductCartHeader_1),
            http("request_11")
              .get("/api/v1/content/pages/?page=0&count=20&store=DEFAULT&lang=en")
              .headers(openTableProductCartHeader_1),
            http("request_12")
              .get("/api/v1/category/?count=20&page=0&store=DEFAULT&lang=en")
              .headers(openTableProductCartHeader_1),
            http("request_13")
              .get("/api/v1/products/1?lang=en&store=DEFAULT")
              .headers(openTableProductCartHeader_1),
            http("request_14")
              .options("/api/v1/product/1/price/")
              .headers(openTableProductCartHeader_2),
            http("request_15")
              .post("/api/v1/product/1/price/")
              .headers(openTableProductCartHeader_3)
              .body(RawFileBody("json_files/step3/0015_request.json"))
          )
      )
    }

  def addTableToCart() : ChainBuilder = {
    exec(
      http("4. Add table to Cart")
        .options("/api/v1/cart/?store=DEFAULT")
        .headers(addTableToCartHeader_0)
        .resources(
          http("request_1")
            .post("/api/v1/cart/?store=DEFAULT")
            .headers(addTableToCartHeader_1)
            .body(RawFileBody("json_files/step4/0001_request.json"))
            .check(jsonPath("$.code").saveAs("code")),
          http("request_2")
            .options("/api/v1/cart/#{code}?lang=en")
            .headers(addTableToCartHeader_2)
        )
    )
  }

  def fiftyPersentOfUsersClickChairsTab() : ChainBuilder = {
    val chairID = getRandomChairID
    val product = chairID match {
      case 50 => "chair1"
      case 51 => "chair2"
      case 52 => "chair3"
    }
    exec(session => session.set("chairID", chairID))
    .exec(session => session.set("product", product))

    .exec(
        http("5. 50% of users")
          .options("/actuator/health/ping")
          .headers(fiftyPersentOfUsersHeaders_0)
          .resources(
            http("request_1")
              .get("/actuator/health/ping")
              .headers(fiftyPersentOfUsersHeaders_1),
            http("request_2")
              .options("/api/v1/content/boxes/headerMessage/?lang=en")
              .headers(fiftyPersentOfUsersHeaders_0),
            http("request_3")
              .options("/api/v1/products/?&store=DEFAULT&lang=en&page=0&count=15&category=51")
              .headers(fiftyPersentOfUsersHeaders_0),
            http("request_4")
              .get("/api/v1/content/boxes/headerMessage/?lang=en")
              .headers(fiftyPersentOfUsersHeaders_1)
              .check(status.is(404)),
            http("request_5")
              .options("/api/v1/store/DEFAULT")
              .headers(fiftyPersentOfUsersHeaders_0),
            http("request_6")
              .options("/api/v1/content/pages/?page=0&count=20&store=DEFAULT&lang=en")
              .headers(fiftyPersentOfUsersHeaders_0),
            http("request_7")
              .options("/api/v1/category/?count=20&page=0&store=DEFAULT&lang=en")
              .headers(fiftyPersentOfUsersHeaders_0),
            http("request_8")
              .get("/api/v1/store/DEFAULT")
              .headers(fiftyPersentOfUsersHeaders_1),
            http("request_9")
              .get("/api/v1/products/?&store=DEFAULT&lang=en&page=0&count=15&category=51")
              .headers(fiftyPersentOfUsersHeaders_1),
            http("request_10")
              .get("/api/v1/content/pages/?page=0&count=20&store=DEFAULT&lang=en")
              .headers(fiftyPersentOfUsersHeaders_1),
            http("request_11")
              .get("/api/v1/category/?count=20&page=0&store=DEFAULT&lang=en")
              .headers(fiftyPersentOfUsersHeaders_1),
            http("request_12")
              .options("/api/v1/product/52/price/")
              .headers(fiftyPersentOfUsersHeaders_2),
            http("request_13")
              .options("/api/v1/category/${chairID}?store=DEFAULT&lang=en")
              .headers(fiftyPersentOfUsersHeaders_0),
            http("request_14")
              .options("/api/v1/product/50/price/")
              .headers(fiftyPersentOfUsersHeaders_2),
            http("request_15")
              .options("/api/v1/product/${chairID}/price/")
              .headers(fiftyPersentOfUsersHeaders_2),
            http("request_16")
              .get("/api/v1/category/51?store=DEFAULT&lang=en")
              .headers(fiftyPersentOfUsersHeaders_1),
            http("request_17")
              .post("/api/v1/product/52/price/")
              .headers(fiftyPersentOfUsersHeaders_3)
              .body(RawFileBody("json_files/step5/0017_request.json")),
            http("request_18")
              .post("/api/v1/product/51/price/")
              .headers(fiftyPersentOfUsersHeaders_3)
              .body(RawFileBody("json_files/step5/0018_request.json")),
            http("request_19")
              .post("/api/v1/product/50/price/")
              .headers(fiftyPersentOfUsersHeaders_3)
              .body(RawFileBody("json_files/step5/0019_request.json")),
            http("request_20")
              .options("/api/v1/category/51/manufacturers/?store=DEFAULT&lang=en")
              .headers(fiftyPersentOfUsersHeaders_0),
            http("request_21")
              .get("/api/v1/category/51/manufacturers/?store=DEFAULT&lang=en")
              .headers(fiftyPersentOfUsersHeaders_1),
            http("request_22")
              .get("/api/v1/category/51/variants/?store=DEFAULT&lang=en")
              .headers(fiftyPersentOfUsersHeaders_1)
              .check(status.is(404))
          )
      )
  }

  def fiftyPersentOfUsersOpenRandomChair() : ChainBuilder = {
    exec(
      http("request_24")
        .get("/actuator/health/ping")
        .headers(fiftyPersentOfUsersHeaders_1)
        .resources(
          http("request_25")
            .get("/api/v1/content/boxes/headerMessage/?lang=en")
            .headers(fiftyPersentOfUsersHeaders_1)
            .check(status.is(404)),
          http("request_26")
            .options("/api/v1/products/${chairID}?lang=en&store=DEFAULT")
            .headers(fiftyPersentOfUsersHeaders_0),
          http("request_27")
            .options("/api/v1/products/${chairID}/reviews?store=DEFAULT")
            .headers(fiftyPersentOfUsersHeaders_0),
          http("request_28")
            .get("/api/v1/store/DEFAULT")
            .headers(fiftyPersentOfUsersHeaders_1),
          http("request_29")
            .get("/api/v1/content/pages/?page=0&count=20&store=DEFAULT&lang=en")
            .headers(fiftyPersentOfUsersHeaders_1),
          http("request_30")
            .get("/api/v1/category/?count=20&page=0&store=DEFAULT&lang=en")
            .headers(fiftyPersentOfUsersHeaders_1),
          http("request_31")
            .get("/api/v1/products/${chairID}/reviews?store=DEFAULT")
            .headers(fiftyPersentOfUsersHeaders_1),
          http("request_32")
            .get("/api/v1/products/${chairID}?lang=en&store=DEFAULT")
            .headers(fiftyPersentOfUsersHeaders_1),
          http("request_33")
            .post("/api/v1/product/${chairID}/price/")
            .headers(fiftyPersentOfUsersHeaders_3)
            .body(RawFileBody("json_files/step5/0033_request.json"))
        )
    )
  }

  def fiftyPersentOfUsersAddChairToCart() : ChainBuilder = {
    exec(
      http("request_35")
        .options("/api/v1/cart/${code}?store=DEFAULT")
        .headers(fiftyPersentOfUsersHeaders_5)
        .resources(
          http("request_36")
            .put("/api/v1/cart/${code}?store=DEFAULT")
            .headers(fiftyPersentOfUsersHeaders_3)
            .body(ElFileBody("json_files/step5/0036_request.json")),
          http("request_37")
            .options("/api/v1/cart/${code}?lang=en")
            .headers(fiftyPersentOfUsersHeaders_0),
          http("request_38")
            .get("/api/v1/cart/${code}?lang=en")
            .headers(fiftyPersentOfUsersHeaders_1)
        )
    )
  }

  def thirtyPersentOfUsersOpenCart(): ChainBuilder = {
    exec(
      http("6. 30% of all users")
        .options("/actuator/health/ping")
        .headers(thirtyPersentOfUsersHeader_0)
        .resources(
          http("request_1")
            .get("/actuator/health/ping")
            .headers(thirtyPersentOfUsersHeader_1),
          http("request_2")
            .options("/api/v1/content/boxes/headerMessage/?lang=en")
            .headers(thirtyPersentOfUsersHeader_0),
          http("request_3")
            .options("/api/v1/cart/${code}?store=DEFAULT")
            .headers(thirtyPersentOfUsersHeader_0),
          http("request_4")
            .options("/api/v1/cart/#{code}?store=DEFAULT")
            .headers(thirtyPersentOfUsersHeader_0),
          http("request_5")
            .options("/api/v1/store/DEFAULT")
            .headers(thirtyPersentOfUsersHeader_0),
          http("request_6")
            .options("/api/v1/category/?count=20&page=0&store=DEFAULT&lang=en")
            .headers(thirtyPersentOfUsersHeader_0),
          http("request_7")
            .get("/api/v1/content/boxes/headerMessage/?lang=en")
            .headers(thirtyPersentOfUsersHeader_1)
            .check(status.is(404)),
          http("request_8")
            .options("/api/v1/content/pages/?page=0&count=20&store=DEFAULT&lang=en")
            .headers(thirtyPersentOfUsersHeader_0),
          http("request_9")
            .get("/api/v1/store/DEFAULT")
            .headers(thirtyPersentOfUsersHeader_1),
          http("request_10")
            .get("/api/v1/category/?count=20&page=0&store=DEFAULT&lang=en")
            .headers(thirtyPersentOfUsersHeader_1),
          http("request_11")
            .get("/api/v1/cart/${code}?store=DEFAULT")
            .headers(thirtyPersentOfUsersHeader_1),
          http("request_12")
            .get("/api/v1/content/pages/?page=0&count=20&store=DEFAULT&lang=en")
            .headers(thirtyPersentOfUsersHeader_1),
          http("request_13")
            .get("/api/v1/cart/${code}?store=DEFAULT")
            .headers(thirtyPersentOfUsersHeader_1)
        )
    )
  }

    def thirtyPersentOfUsersProceedToCheckout(): ChainBuilder = {
      exec(
        http("request_14")
          .get("/actuator/health/ping")
          .headers(thirtyPersentOfUsersHeader_1)
          .resources(
            http("request_15")
              .get("/api/v1/content/boxes/headerMessage/?lang=en")
              .headers(thirtyPersentOfUsersHeader_1)
              .check(status.is(404)),
            http("request_16")
              .options("/api/v1/shipping/country?store=DEFAULT&lang=en")
              .headers(thirtyPersentOfUsersHeader_0),
            http("request_17")
              .options("/api/v1/zones/?code=")
              .headers(thirtyPersentOfUsersHeader_0),
            http("request_18")
              .options("/api/v1/zones/?code=")
              .headers(thirtyPersentOfUsersHeader_0),
            http("request_19")
              .get("/api/v1/store/DEFAULT")
              .headers(thirtyPersentOfUsersHeader_1),
            http("request_20")
              .options("/api/v1/config/")
              .headers(thirtyPersentOfUsersHeader_0),
            http("request_21")
              .options("/api/v1/cart/${code}/shipping")
              .headers(thirtyPersentOfUsersHeader_2),
            http("request_22")
              .options("/api/v1/cart/${code}/total/")
              .headers(thirtyPersentOfUsersHeader_0),
            http("request_23")
              .get("/api/v1/cart/${code}?store=DEFAULT")
              .headers(thirtyPersentOfUsersHeader_1),
            http("request_24")
              .get("/api/v1/content/pages/?page=0&count=20&store=DEFAULT&lang=en")
              .headers(thirtyPersentOfUsersHeader_1),
            http("request_25")
              .get("/api/v1/category/?count=20&page=0&store=DEFAULT&lang=en")
              .headers(thirtyPersentOfUsersHeader_1),
            http("request_26")
              .get("/api/v1/zones/?code=")
              .headers(thirtyPersentOfUsersHeader_1),
            http("request_27")
              .get("/api/v1/zones/?code=")
              .headers(thirtyPersentOfUsersHeader_1),
            http("request_28")
              .get("/api/v1/shipping/country?store=DEFAULT&lang=en")
              .headers(thirtyPersentOfUsersHeader_1),
            http("request_29")
              .get("/api/v1/config/")
              .headers(thirtyPersentOfUsersHeader_1),
            http("request_30")
              .post("/api/v1/cart/${code}/shipping")
              .headers(thirtyPersentOfUsersHeader_3)
              .body(RawFileBody("json_files/step6/0030_request.json"))
              .check(status.is(503)),
            http("request_31")
              .get("/api/v1/cart/${code}/total/")
              .headers(thirtyPersentOfUsersHeader_1)
          )
    )
  }
}